name: ReactCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.16.2]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run:  yarn build
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "iignaciovelasco@gmail.com>"
        git config --global user.name "IgVelasco>"
        yarn start
