name: ReactCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.16.2]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run:  yarn install
    - name: Build packages
      run:  yarn build
  # - name: Deploy to GH Pages
   #   run: |
    #    git config --global user.email "iignaciovelasco@gmail.com>"
     #   git config --global user.name "IgVelasco>"
      #  https://0d5f826cbc0de0d498821c96b5a7fc0c4a59507a@github.com/taller2-chotuve-grupo2/web-admin.git
       # yarn start    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
